"""
algo_engine.shadow_pipeline — Supabase Shadow Database Pipeline
===============================================================

Manages streaming and syncing of Black Box signal lifecycle states into
the Supabase `shadow_signals` table for side-by-side parity auditing.
Includes resilient local storage fallback.
"""

from __future__ import annotations
import os
import json
import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
import logging
from dotenv import load_dotenv

from .strategies import StrategySignal
from .trade_manager import Trade, TradeStatus, TradeOutcome
from .feeds import normalize_symbol, get_market_category

logger = logging.getLogger(__name__)

# Load environment variables
load_dotenv()
load_dotenv(os.path.join(os.path.dirname(__file__), ".env"))


class ShadowPipeline:
    """
    Supabase Shadow Signal Pipeline.
    
    Inserts and updates trade lifecycle events in Supabase `shadow_signals`.
    Maintains local disk fallback if table does not yet exist.
    """

    def __init__(self,
                 supabase_url: Optional[str] = None,
                 supabase_key: Optional[str] = None,
                 table_name: Optional[str] = None,
                 dual_write: Optional[bool] = None,
                 local_fallback_path: Optional[str] = None,
                 disable_supabase: bool = False):
        if disable_supabase:
            self.supabase_url = None
            self.supabase_key = None
        else:
            self.supabase_url = supabase_url or os.getenv("SUPABASE_URL")
            self.supabase_key = supabase_key or os.getenv("SUPABASE_KEY")

        self.table_name = table_name or os.getenv("SHADOW_TARGET_TABLE", "shadow_signals")
        
        if dual_write is not None:
            self.dual_write = dual_write
        else:
            self.dual_write = os.getenv("SHADOW_DUAL_WRITE", "false").lower() in ("true", "1", "yes")

        self.local_fallback_path = local_fallback_path or os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "data", "local_shadow_signals.json"
        )

        self._sb = None
        self._table_available: Optional[bool] = None
        self._local_records: List[Dict[str, Any]] = []

        self._init_client()
        self._load_local_fallback()

    def _init_client(self) -> None:
        """Initialize Supabase client if credentials are present."""
        if not self.supabase_url or not self.supabase_key:
            logger.warning("[ShadowPipeline] Missing Supabase credentials. Operating in local fallback mode.")
            return

        try:
            from supabase import create_client
            self._sb = create_client(self.supabase_url, self.supabase_key)
            logger.info("[ShadowPipeline] Supabase client initialized.")
        except Exception as e:
            logger.error(f"[ShadowPipeline] Failed to create Supabase client: {e}")

    def _load_local_fallback(self) -> None:
        """Load local fallback storage if it exists."""
        if os.path.exists(self.local_fallback_path):
            try:
                with open(self.local_fallback_path, "r") as f:
                    self._local_records = json.load(f)
            except Exception as e:
                logger.warning(f"[ShadowPipeline] Could not load local fallback: {e}")

    def _save_local_fallback(self) -> None:
        """Persist local fallback storage to disk."""
        try:
            os.makedirs(os.path.dirname(self.local_fallback_path), exist_ok=True)
            with open(self.local_fallback_path, "w") as f:
                json.dump(self._local_records, f, indent=2, default=str)
        except Exception as e:
            logger.error(f"[ShadowPipeline] Error saving local fallback: {e}")

    # ── Signal Lifecycle Storage Methods ─────────────────────────

    def record_signal(self, signal: StrategySignal, symbol: str) -> Optional[str]:
        """
        Record a newly spawned trade signal (limit order).
        
        Args:
            signal: StrategySignal generated by strategy engine
            symbol: Raw or normalized symbol
            
        Returns:
            Generated trade_id
        """
        clean_sym = normalize_symbol(symbol)
        mkt = get_market_category(clean_sym)
        now_iso = datetime.now(timezone.utc).isoformat()
        trade_id = f"{clean_sym}_{int(time.time() * 1000)}_{signal.name}"

        payload = {
            "symbol": clean_sym,
            "type": signal.name,
            "entry": round(signal.entry_price, 4),
            "stop": round(signal.stop_loss, 4),
            "target": round(signal.tp1, 4),
            "tp2": round(signal.tp2, 4),
            "tp3": round(signal.tp3, 4),
            "tp4": round(signal.tp4, 4),
            "status": "OPEN",
            "outcome": "OPEN",
            "trigger": "TradeOpen",
            "pricing_type": "SHADOW",
            "source": "BLACKBOX",
            "exchange": mkt,
            "signal_ts": now_iso,
            "created_at": now_iso,
            "updated_at": now_iso,
            "metadata": {
                "trade_id": trade_id,
                "zone": signal.zone,
                "opening_bias": signal.opening_bias,
                "day_type": signal.day_type,
                "engine_version": "2.0.0",
            }
        }

        self._execute_insert(trade_id, payload)
        logger.info(f"[ShadowPipeline] Recorded new signal: {signal.name} for {clean_sym} at {signal.entry_price}")
        return trade_id

    def sync_signal(self, sig: dict) -> None:
        """
        Record a scanner-detected active signal into shadow_signals.
        """
        sym = normalize_symbol(sig.get("symbol", ""))
        now_iso = datetime.now(timezone.utc).isoformat()
        trade_id = f"SCAN_{sym}_{int(time.time() * 1000)}_{sig.get('type', 'SIG')}"

        payload = {
            "symbol": sym,
            "type": sig.get("type", "ACTIVE"),
            "entry": round(float(sig.get("entry_price", 0.0)), 4) if sig.get("entry_price") else None,
            "stop": round(float(sig.get("stop_loss", 0.0)), 4) if sig.get("stop_loss") else None,
            "target": round(float(sig.get("tp1", 0.0)), 4) if sig.get("tp1") else None,
            "tp2": round(float(sig.get("tp2", 0.0)), 4) if sig.get("tp2") else None,
            "tp3": round(float(sig.get("tp3", 0.0)), 4) if sig.get("tp3") else None,
            "tp4": round(float(sig.get("tp4", 0.0)), 4) if sig.get("tp4") else None,
            "status": "ACTIVE",
            "outcome": "OPEN",
            "trigger": sig.get("trigger", "ScannerAlert"),
            "pricing_type": "SHADOW",
            "source": "blackbox_dhan",
            "exchange": "nifty",
            "signal_ts": sig.get("created_at", now_iso),
            "created_at": sig.get("created_at", now_iso),
            "updated_at": now_iso,
            "metadata": {
                "trade_id": trade_id,
                **(sig.get("metadata") or {}),
                "engine_version": "3.0.0"
            }
        }
        self._execute_insert(trade_id, payload)

    def record_fill(self, trade: Trade) -> None:
        """Record limit order execution / fill."""
        now_iso = datetime.now(timezone.utc).isoformat()
        payload = {
            "status": "⚡ TRADE ACTIVE",
            "trigger": "TradeFill",
            "updated_at": now_iso,
            "metadata": {
                "trade_id": trade.trade_id,
                "real_entry_time": now_iso,
            }
        }
        self._execute_update(trade.trade_id, payload)
        logger.info(f"[ShadowPipeline] Trade filled: {trade.name} for {trade.symbol} at {trade.entry_price}")

    def record_trail_update(self, trade: Trade) -> None:
        """Record dynamic trailing stop adjustment."""
        now_iso = datetime.now(timezone.utc).isoformat()
        payload = {
            "trail_sl": round(trade.current_sl, 4),
            "trailing_stop": round(trade.current_sl, 4),
            "status": "Trailing Stop",
            "trigger": "TrailingSL",
            "updated_at": now_iso,
        }
        self._execute_update(trade.trade_id, payload)
        logger.info(f"[ShadowPipeline] Trailing stop updated: {trade.symbol} to {trade.current_sl}")

    def record_trade_close(self, trade: Trade) -> None:
        """
        Record trade settlement and inject exact_pct.
        
        Single Source of Truth: exact_pct = ((Exit - Entry) / Entry) * 100
        """
        now_iso = datetime.now(timezone.utc).isoformat()
        exact_pct = trade.exact_pct

        # Map TradeOutcome to string
        outcome_str = trade.outcome.value

        # Status label
        if outcome_str == "WIN":
            status_str = f"Hit {trade.exit_level}" if trade.exit_level.startswith("TP") else "Hit Target"
        elif outcome_str == "LOSS":
            status_str = "Hit Initial SL" if trade.exit_level == "SL" else f"Hit {trade.exit_level}"
        elif outcome_str == "BREAKEVEN":
            status_str = "Hit B/E"
        elif outcome_str == "CANCELLED":
            status_str = "CANCELLED"
        else:
            status_str = trade.exit_level or "Closed"

        payload = {
            "status": status_str,
            "outcome": outcome_str,
            "exit_price": round(trade.exit_price, 4) if trade.exit_price is not None else None,
            "exit_at": now_iso,
            "trigger": "TradeExit",
            "updated_at": now_iso,
            "metadata": {
                "trade_id": trade.trade_id,
                "exact_pct": exact_pct,
                "exit_level": trade.exit_level,
                "close_date": now_iso,
            }
        }
        self._execute_update(trade.trade_id, payload)
        logger.info(f"[ShadowPipeline] Trade closed: {trade.symbol} {trade.name} | Outcome: {outcome_str} | Return: {exact_pct}%")

    # ── Underlying Persistence Handlers ──────────────────────────

    def _execute_insert(self, trade_id: str, payload: Dict[str, Any]) -> None:
        """Insert into Supabase shadow table (and signals if dual_write) or local fallback."""
        if self._sb and self._table_available is not False:
            try:
                res = self._sb.from_(self.table_name).insert(payload).execute()
                self._table_available = True
            except Exception as e:
                err_msg = str(e)
                if "Could not find the table" in err_msg or "PGRST205" in err_msg:
                    self._table_available = False
                    logger.warning(
                        f"[ShadowPipeline] Supabase table '{self.table_name}' does not exist yet. "
                        f"Run 'algo_engine/sql/create_shadow_signals.sql' in Supabase SQL Editor. "
                        f"Buffering to local storage."
                    )
                else:
                    logger.error(f"[ShadowPipeline] Error inserting into {self.table_name}: {e}")

            # Dual-write to signals table so mobile app & web dashboard see live trades
            if self.dual_write and self.table_name != "signals":
                try:
                    self._sb.from_("signals").insert(payload).execute()
                    logger.info(f"[ShadowPipeline] Dual-write: inserted {trade_id} into public.signals")
                except Exception as e2:
                    logger.error(f"[ShadowPipeline] Dual-write to signals failed: {e2}")

            if self._table_available:
                return

        # Local storage fallback
        payload["id"] = trade_id
        self._local_records.insert(0, payload)
        self._save_local_fallback()

    def _execute_update(self, trade_id: str, payload: Dict[str, Any]) -> None:
        """Update existing row in Supabase shadow table (and signals if dual_write) or local fallback."""
        if self._sb and self._table_available is not False:
            try:
                self._sb.from_(self.table_name).update(payload).eq("metadata->>trade_id", trade_id).execute()
            except Exception as e:
                logger.error(f"[ShadowPipeline] Error updating {self.table_name}: {e}")

            # Dual-write update to signals table
            if self.dual_write and self.table_name != "signals":
                try:
                    self._sb.from_("signals").update(payload).eq("metadata->>trade_id", trade_id).execute()
                    logger.info(f"[ShadowPipeline] Dual-write: updated {trade_id} in public.signals")
                except Exception as e2:
                    logger.error(f"[ShadowPipeline] Dual-write update to signals failed: {e2}")

            return
        for row in self._local_records:
            meta = row.get("metadata", {})
            if meta.get("trade_id") == trade_id or row.get("id") == trade_id:
                row.update(payload)
                if "metadata" in payload:
                    row["metadata"].update(payload["metadata"])
                self._save_local_fallback()
                return

    def get_recent_signals(self, limit: int = 50) -> List[Dict[str, Any]]:
        """Fetch recent signals for parity audit display."""
        if self._sb and self._table_available is not False:
            try:
                res = self._sb.from_(self.table_name).select("*").order("created_at", desc=True).limit(limit).execute()
                if res.data:
                    return res.data
            except Exception as e:
                logger.debug(f"[ShadowPipeline] Query error: {e}")

        return self._local_records[:limit]
